# config.py

DEFAULT_VALUES = {
    'x_train_file': './tests/data/encoder_eval.csv',
    'y_train_file': './tests/data/csv_sel_unb_norm_512.csv',
    'x_validation_file': None,
    'y_validation_file': None,
    'target_column': None,
    'output_file': './csv_output.csv',
    'save_model': './model.keras',
    'load_model': None,
    'evaluate_file': './model_eval.csv',
    'optimizer_plugin': 'neat',
    'environment_plugin': 'prediction_plugin',
    'agent_plugin': 'agent_predictor',
    'remote_log': None,
    'remote_load_config': None,
    'remote_save_config': None,
    'username': None,
    'password': None,
    'load_config': None,
    'save_config': './config_out.json',
    'save_log': './debug_out.json',
    'quiet_mode': False,
    'force_date': False,
    'headers': True,
    'max_steps': 10000,
}
